apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: postgresql
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30004
