# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
  service:
    enabled: true
    type: NodePort
    nodePort: 30002

grafana:
  adminPassword: kaasbal
  sidecar:
      dashboards:
        enabled: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  service:
    enabled: true
    type: NodePort
    nodePort: 30001